# Se configura la conexión a la base de datos utilizando el conector MySQL oficial
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/almacen_trazabilidad?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de JPA y SSL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8443
server.ssl.key-store=classpath:keystore_seguro.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=trazabilidad-ssl
